---
title: "Election results from Canadian Federal elections in 2011"
output: 
  html_document:
    keep_md: true
---

How signigicant was conservative lead?

```{r, message=FALSE}
# Analyze election results from Canadian Federal Elections 2011

library(readr)
library(dplyr)

#setwd(file.path(normalizePath("~"),"elections"))
```

```{r}
## Get data
remote <- 
        "http://www.elections.ca/scripts/OVR2011/34/data_donnees/table_tableau12.csv"
#local<-basename(remote)
#if(!file.exists(local)) download.file(remote, local, mode="wb")
#e <- read_csv(local)
# Use remote directly to skip mode setting problem
e <- read_csv(remote)



## Clean data

# Vectorized function to drop everything after first slash - normally French
# location names - and replace spaces with dots

vEnglishize <- function(strings.vector, replace.spaces = FALSE) {
        sapply(strings.vector, 
               function(s) {
                        x <- strsplit(s, "/", fixed=TRUE) %>% unlist
                        x <- trimws(x[1])
                        if (replace.spaces) x <- gsub(" ", ".", x, fixed=TRUE)
                        return(x)
               }
        )
}

colnames(e) %>% vEnglishize(replace.spaces=TRUE) -> colnames(e)
e$Province %>% vEnglishize -> e$Province
e$Candidate %>% vEnglishize -> e$Candidate
e$Candidate.Residence %>% vEnglishize -> e$Candidate.Residence

numerize <- function(x) {
        x %>% trimws %>% as.numeric
}

e$Majority %>% numerize -> e$Majority
e$Majority.Percentage %>% numerize -> e$Majority.Percentage

## What are the most partisan places?

e %>% 
        arrange(desc(Percentage.of.Votes.Obtained)) %>%
        head(10) %>%
        glimpse

## What about BC?

e[e$Province=="British Columbia", ] %>%
        arrange(desc(Percentage.of.Votes.Obtained)) %>%
        head(10) %>%
        glimpse

stdev <- sd(e$Percentage.of.Votes.Obtained)
aver  <- mean(e$Percentage.of.Votes.Obtained)
cat(paste("If the distribution would be normal, 68% of winning candidates would get",
          round(aver - stdev),
          "to",
          round(aver + stdev),
          "percents of votes"))
hist(e$Percentage.of.Votes.Obtained,
     main = "Is it hard to get 50% of votes?",
     xlab = "Percentage of votes",
     ylab = "Number of candidates")

# Let's see what distribution is for winners

winners <- tapply(e$Percentage.of.Votes.Obtained,
                  e$Electoral.District.Number,
                  max)

hist(winners,
     main = "Lead of winners",
     xlab = "Percentage of votes",
     ylab = "Number of candidates")

stdev <- sd(winners)
aver <- mean(winners)
cat(paste("If the distribution would be normal, 68% of winning candidates would get",
          round(aver - stdev),
          "to",
          round(aver + stdev),
          "percents of votes"))
```

Let's check Benford's law
```{r}

vFirstDigit <- function(numbers.vector) {
        sapply(numbers.vector, function(x) {
                if (x != 0) {
                        while (x < 1) x <- x*10
                        x %>% as.character %>% substr(1,1) %>% as.integer -> x
                        }
                return(x)
                })
}

hist(vFirstDigit(e$Percentage.of.Votes.Obtained),
     main="Benford's law tested for percentages of votes for all candidates",
     xlab="First digits of vote percentages",
     breaks=1:9,
     xaxt="n")
axis(1,at=1:9,hadj=-4)

hist(vFirstDigit(winners),
     main="Benford's law tested for percentages of votes for winning candidates",
     xlab="First digits of vote percentages",
     breaks=1:9,
     xaxt="n")
axis(1,at=1:9,hadj=-4)
```